### ISSUE TITLE
Installation issue - Syntax error unexpected token

### ISSUE THREAD

**Issue by physicsnerd** [rishiosaur/hoot-cli#14]
Found out about your project on the hack club slack and seemed pretty cool, so I decided to install.

This could be a problem with my system, not with your program. I'm running ubuntu 16.04 dual booted on a chromebook. Installed nodejs, then nodejs-legacy, then npm, then ran the installation command. This worked, but gave the following warnings:

```
WARN engine inquirer@6.5.2: wanted: {"node":">=6.0.0"} (current: {"node":"4.2.6"loadDep:shelljs -> resolv \ |##########---------------------------------------|
WARN engine fs-extra@8.1.0: wanted: {"node":">=6 <7 || >=8"} (current: {"node":"loadDep:through -> addNam \ |###############----------------------------------|
WARN engine strip-ansi@5.2.0: wanted: {"node":">=6"} (current: {"node":"4.2.6","loadDep:ansi-regex -> aft / |################---------------------------------|
WARN engine ansi-regex@4.1.0: wanted: {"node":">=6"} (current: {"node":"4.2.6","/usr/local/bin/hoot -> /usr/local/lib/node_modules/hoot-cli/bin/index.js
```

I proceeded to run `hoot setup` and got

```
const { makeAssignment }  = require("./commands/assignments/makeAssignment")
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by rishiosaur** [comment]
Hmm, it looks like you're running an older version of `node`. Try updating, and see if it works then!
